server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-management-service
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/bookings/**
        
        - id: flight-service
          uri: lb://flight-management-service
          predicates:
            - Path=/api/flights/**, /seat-map/**
            
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
